<!-- 
<link rel="shortcut icon" type="image/png"  href="${contextPath}/resources/img/logo_swan01.png">
 -->
<script src="${contextPath}/resources/lib/jquery/jquery-3.2.1.min.js"></script>

<link rel="stylesheet" type="text/css" href="${contextPath}/resources/lib/bootstrap-3.3.2-dist/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="${contextPath}/resources/lib/bootstrap-3.3.2-dist/css/bootstrap-theme.min.css" />
<script charset="utf-8" src="${contextPath}/resources/lib/bootstrap-3.3.2-dist/js/bootstrap.min.js"></script>

<script>
$(function(){
document.title = '${user.getServicename()}';
});
</script>
