	
	<!-- default -->
	<link rel="stylesheet" type="text/css" href="${contextPath}/resources/external/jquery.ui/css/jquery-ui.css" />
	<!-- <link rel="stylesheet" type="text/css" href="${contextPath}/resources/external/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="${contextPath}/resources/external/skin/skin-rawris.css" />  -->
	<link rel="stylesheet" type="text/css" href="${contextPath}/resources/wrms/css/wrms_default.css?v=1.03" />
	<link rel="stylesheet" href="${contextPath}/resources/external/font/font-awesome/css/font-awesome.min.css" />
	<link rel="stylesheet" href="${contextPath}/resources/external/datepicker/jquery.datetimepicker.min.css" />


	
	<script src="${contextPath}/resources/external/jquery/jQuery-2.1.4.min.js"></script> 
	<script src="${contextPath}/resources/external/jquery.ui/js/jquery-ui.min.js"></script> 
	<script src="${contextPath}/resources/external/jquery.block.ui/jquery.blockUI.js"></script>
	<script src="<c:url value='/resources/external/jquery.number/jquery.number.min.js'/>"></script> 
    <script src="${contextPath}/resources/external/bootstrap/js/bootstrap.min.js"></script>
    
    <script src="${contextPath}/resources/external/datepicker/jquery.datetimepicker.full.min.js"></script>
    <script src="${contextPath}/resources/external/daterangepicker/daterangepicker.js"></script>
    
    <script src="${contextPath}/resources/wrms/js/commonUtils.js"></script>
    <script src="${contextPath}/resources/wrms/js/searchForm.js"></script>
    
    <!-- leaflet && windy -->
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="https://api.windy.com/assets/map-forecast/libBoot.js"></script>
    
    <!-- leaflet 위치검색 -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>