
	<!-- jsGRID component -->
	<link rel="stylesheet" href="${contextPath}/resources/external/jsgrid-1.5.3/jsgrid.css"/>
	<link rel="stylesheet" href="${contextPath}/resources/external/jsgrid-1.5.3/jsgrid-theme.css" />
	<link rel="stylesheet" href="${contextPath}/resources/wrms/css/jsgrid-theme.css?v=1.05" />
	
	<script type="text/javascript" src="${contextPath}/resources/external/jsgrid-1.5.3/jsgrid.js"></script>
	<script type="text/javascript" src="${contextPath}/resources/external/jsgrid-1.5.3/jsgrid.ext.js"></script>
	<script type="text/javascript" src="${contextPath}/resources/wrms/js/jsgrid_ext2.js?v=1.02"></script>