
	<!-- zingchart -->
    <script src="${contextPath}/resources/external/zingchart/js_new/zingchart.min.js"></script>
    <script src="${contextPath}/resources/external/zingchart/js_new/zingchart-selection.min.js"></script>
    <script src="${contextPath}/resources/external/zingchart/js_new/zingchart-selection-tool.min.js"></script>
	<script>ZC.LICENSE = ['27e8d67301e3d716acfc9e1287a15f29'];</script> 