// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class BasinInfowOutput_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected BasinInfowOutput_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public BasinInfowOutput_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.BasinInfowOutput_cs.__ctorBasinInfowOutput_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorBasinInfowOutput_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()S")
    public native short getYear();
    
    @net.sf.jni4net.attributes.ClrMethod("(S)V")
    public native void setYear(short year);
    
    @net.sf.jni4net.attributes.ClrMethod("()B")
    public native byte getMonth();
    
    @net.sf.jni4net.attributes.ClrMethod("(B)V")
    public native void setMonth(byte month);
    
    @net.sf.jni4net.attributes.ClrMethod("()B")
    public native byte getDay();
    
    @net.sf.jni4net.attributes.ClrMethod("(B)V")
    public native void setDay(byte day);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRainfall();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRainfall(double rainfall);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getInfowQmm();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setInfowQmm(double infowQmm);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getInfowQcms();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setInfowQcms(double infowQcms);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/DateTime;")
    public native system.DateTime getDate();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/DateTime;)V")
    public native void setDate(system.DateTime date);
    
    public static system.Type typeof() {
        return cshapjni.BasinInfowOutput_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.BasinInfowOutput_cs.staticType = staticType;
    }
    //</generated-proxy>
}
