// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class BasinInfowInput_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected BasinInfowInput_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public BasinInfowInput_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.BasinInfowInput_cs.__ctorBasinInfowInput_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorBasinInfowInput_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getBasinAreaHa();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setBasinAreaHa(double basinAreaHa);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRatioPaddy();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRatioPaddy(double ratioPaddy);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRatioUplnd();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRatioUplnd(double ratioUplnd);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRatioForest();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRatioForest(double ratioForest);
    
    public static system.Type typeof() {
        return cshapjni.BasinInfowInput_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.BasinInfowInput_cs.staticType = staticType;
    }
    //</generated-proxy>
}
