// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class Cshap_Jni extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Cshap_Jni(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Cshap_Jni() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.Cshap_Jni.__ctorCshap_Jni0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorCshap_Jni0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LCshapJni/FloodReservoir_cs;LCshapJni/FloodBasin_cs;[DDI)[LCshapJni/FloodResult_cs;")
    public native cshapjni.FloodResult_cs[] GetFloodDatas_jni(cshapjni.FloodReservoir_cs FloodReservoir_jni, cshapjni.FloodBasin_cs FloodBasin_jni, double[] rains, double dt, int utype);
    
    @net.sf.jni4net.attributes.ClrMethod("([LCshapJni/ReservoirWaterRateForecastInput_cs;)[LCshapJni/ReservoirWaterRateForecastOutput_cs;")
    public native cshapjni.ReservoirWaterRateForecastOutput_cs[] CalReservoirWaterRateForecast_jni(cshapjni.ReservoirWaterRateForecastInput_cs[] ReservoirWaterRateForecastInput_jni);
    
    @net.sf.jni4net.attributes.ClrMethod("([LCshapJni/MeteoDailyData_cs;LCshapJni/WreqPaddyInput_cs;LCshapJni/StationInput_cs;)[LCshapJni/WreqPaddyOutput_cs;")
    public native cshapjni.WreqPaddyOutput_cs[] CalDailyPaddy_jni(cshapjni.MeteoDailyData_cs[] MeteoDailyData_jni, cshapjni.WreqPaddyInput_cs WreqPaddyInput_jni, cshapjni.StationInput_cs StationInput_jni);
    
    @net.sf.jni4net.attributes.ClrMethod("([LCshapJni/MeteoDailyData_cs;LCshapJni/BasinInfowInput_cs;)[LCshapJni/BasinInfowOutput_cs;")
    public native static cshapjni.BasinInfowOutput_cs[] RunByDIROM_jni(cshapjni.MeteoDailyData_cs[] MeteoDailyData_jni, cshapjni.BasinInfowInput_cs BasinInfowInput_jni);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native java.lang.String jni_Test(java.lang.String str);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)[LCshapJni/BasinInfowOutput_cs;")
    public native cshapjni.BasinInfowOutput_cs[] jni_Test_2(java.lang.String str);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)[LCshapJni/BasinInfowOutput_cs;")
    public native cshapjni.BasinInfowOutput_cs[] jni_BasinInfowOutput(java.lang.String str);
    
    public static system.Type typeof() {
        return cshapjni.Cshap_Jni.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.Cshap_Jni.staticType = staticType;
    }
    //</generated-proxy>
}
