// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class FloodReservoir_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected FloodReservoir_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public FloodReservoir_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.FloodReservoir_cs.__ctorFloodReservoir_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorFloodReservoir_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double get_elevation();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void set_elevation(double elevation);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double get_level_dead();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void set_level_dead(double level_dead);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double get_level_flood();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void set_level_flood(double level_flood);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double get_level_full();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void set_level_full(double level_full);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double get_level_now();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void set_level_now(double level_now);
    
    @net.sf.jni4net.attributes.ClrMethod("()[D")
    public native double[] get_linears();
    
    @net.sf.jni4net.attributes.ClrMethod("([D)V")
    public native void set_linears(double[] linears);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LCshapJni/FloodReservoirSpillGate_cs;")
    public native cshapjni.FloodReservoirSpillGate_cs[] get_spillGates();
    
    @net.sf.jni4net.attributes.ClrMethod("([LCshapJni/FloodReservoirSpillGate_cs;)V")
    public native void set_spillGates(cshapjni.FloodReservoirSpillGate_cs[] spillGates);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LCshapJni/FloodReservoirSpillWeir_cs;")
    public native cshapjni.FloodReservoirSpillWeir_cs[] get_spillWeirs();
    
    @net.sf.jni4net.attributes.ClrMethod("([LCshapJni/FloodReservoirSpillWeir_cs;)V")
    public native void set_spillWeirs(cshapjni.FloodReservoirSpillWeir_cs[] spillWeirs);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LCshapJni/FloodReservoirWeir_cs;")
    public native cshapjni.FloodReservoirWeir_cs[] get_weirs();
    
    @net.sf.jni4net.attributes.ClrMethod("([LCshapJni/FloodReservoirWeir_cs;)V")
    public native void set_weirs(cshapjni.FloodReservoirWeir_cs[] weirs);
    
    public static system.Type typeof() {
        return cshapjni.FloodReservoir_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.FloodReservoir_cs.staticType = staticType;
    }
    //</generated-proxy>
}
