// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class MeteoDailyData_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected MeteoDailyData_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public MeteoDailyData_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.MeteoDailyData_cs.__ctorMeteoDailyData_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorMeteoDailyData_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()S")
    public native short getYear();
    
    @net.sf.jni4net.attributes.ClrMethod("(S)V")
    public native void setYear(short year);
    
    @net.sf.jni4net.attributes.ClrMethod("()B")
    public native byte getMonth();
    
    @net.sf.jni4net.attributes.ClrMethod("(B)V")
    public native void setMonth(byte month);
    
    @net.sf.jni4net.attributes.ClrMethod("()B")
    public native byte getDay();
    
    @net.sf.jni4net.attributes.ClrMethod("(B)V")
    public native void setDay(byte day);
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getRainfall();
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void setRainfall(float rainfall);
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getEvapor();
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void setEvapor(float evapor);
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getTemperature();
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void setTemperature(float temperature);
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getHumidity();
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void setHumidity(float humidity);
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getSunhour();
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void setSunhour(float sunhour);
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getWindspeed();
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void setWindspeed(float windspeed);
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getEToPenman();
    
    @net.sf.jni4net.attributes.ClrMethod("(F)V")
    public native void setEToPenman(float eToPenman);
    
    public static system.Type typeof() {
        return cshapjni.MeteoDailyData_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.MeteoDailyData_cs.staticType = staticType;
    }
    //</generated-proxy>
}
