// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class ReservoirWaterRateForecastOutput_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ReservoirWaterRateForecastOutput_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ReservoirWaterRateForecastOutput_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.ReservoirWaterRateForecastOutput_cs.__ctorReservoirWaterRateForecastOutput_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorReservoirWaterRateForecastOutput_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getFacCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setFacCode(java.lang.String facCode);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getVow1();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setVow1(double vow1);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getVow2();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setVow2(double vow2);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getVow3();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setVow3(double vow3);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getFacAvg();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setFacAvg(double facAvg);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRVow();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRVow(double rVow);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRVow1();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRVow1(double rVow1);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRVow2();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRVow2(double rVow2);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getRVow3();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setRVow3(double rVow3);
    
    public static system.Type typeof() {
        return cshapjni.ReservoirWaterRateForecastOutput_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.ReservoirWaterRateForecastOutput_cs.staticType = staticType;
    }
    //</generated-proxy>
}
