// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class ReservoirWaterRateForecastInput_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ReservoirWaterRateForecastInput_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ReservoirWaterRateForecastInput_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.ReservoirWaterRateForecastInput_cs.__ctorReservoirWaterRateForecastInput_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorReservoirWaterRateForecastInput_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getFacCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setFacCode(java.lang.String facCode);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getFacCat();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setFacCat(java.lang.String facCat);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getFacName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setFacName(java.lang.String facName);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getBasinArea();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setBasinArea(double basinArea);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAgrArea();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAgrArea(double agrArea);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getYooHyoy();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setYooHyoy(double yooHyoy);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSigunCd();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setSigunCd(java.lang.String sigunCd);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getVow();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setVow(double vow);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAvgRain1();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAvgRain1(double avgRain1);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAvgRain2();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAvgRain2(double avgRain2);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAvgRain3();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAvgRain3(double avgRain3);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getForeAvgRain1();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setForeAvgRain1(double foreAvgRain1);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getForeAvgRain2();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setForeAvgRain2(double foreAvgRain2);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getForeAvgRain3();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setForeAvgRain3(double foreAvgRain3);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getFacAvg();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setFacAvg(double facAvg);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getFacAvg1();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setFacAvg1(double facAvg1);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getFacAvg2();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setFacAvg2(double facAvg2);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getFacAvg3();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setFacAvg3(double facAvg3);
    
    public static system.Type typeof() {
        return cshapjni.ReservoirWaterRateForecastInput_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.ReservoirWaterRateForecastInput_cs.staticType = staticType;
    }
    //</generated-proxy>
}
