// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class StationInput_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected StationInput_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public StationInput_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.StationInput_cs.__ctorStationInput_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorStationInput_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getMapLat();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setMapLat(double mapLat);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getElevation();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setElevation(double elevation);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getGaugeHeight();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setGaugeHeight(double gaugeHeight);
    
    public static system.Type typeof() {
        return cshapjni.StationInput_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.StationInput_cs.staticType = staticType;
    }
    //</generated-proxy>
}
