// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package cshapjni;

@net.sf.jni4net.attributes.ClrType
public class WreqPaddyInput_cs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected WreqPaddyInput_cs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public WreqPaddyInput_cs() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        cshapjni.WreqPaddyInput_cs.__ctorWreqPaddyInput_cs0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorWreqPaddyInput_cs0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()[D")
    public native double[] getIrrAreaHa();
    
    @net.sf.jni4net.attributes.ClrMethod("([D)V")
    public native void setIrrAreaHa(double[] irrAreaHa);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getNonAreaHa();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setNonAreaHa(double nonAreaHa);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getInfiltMm();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setInfiltMm(double infiltMm);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getChLossPct();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setChLossPct(double chLossPct);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getDepthMaxMm();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setDepthMaxMm(double depthMaxMm);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getDepthMinMm();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setDepthMinMm(double depthMinMm);
    
    @net.sf.jni4net.attributes.ClrMethod("()[D")
    public native double[] getCropCoef();
    
    @net.sf.jni4net.attributes.ClrMethod("([D)V")
    public native void setCropCoef(double[] cropCoef);
    
    @net.sf.jni4net.attributes.ClrMethod("()[S")
    public native short[] getPlanDate();
    
    @net.sf.jni4net.attributes.ClrMethod("([S)V")
    public native void setPlanDate(short[] planDate);
    
    @net.sf.jni4net.attributes.ClrMethod("()[D")
    public native double[] getUnitWReqMm();
    
    @net.sf.jni4net.attributes.ClrMethod("([D)V")
    public native void setUnitWReqMm(double[] unitWReqMm);
    
    public static system.Type typeof() {
        return cshapjni.WreqPaddyInput_cs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        cshapjni.WreqPaddyInput_cs.staticType = staticType;
    }
    //</generated-proxy>
}
