//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class BasinInfowInput_cs_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__BasinInfowInput_cs.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.BasinInfowInput_cs), typeof(global::CshapJni.BasinInfowInput_cs_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.BasinInfowInput_cs), typeof(global::CshapJni.BasinInfowInput_cs_))]
    internal sealed partial class @__BasinInfowInput_cs : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__BasinInfowInput_cs(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__BasinInfowInput_cs.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__BasinInfowInput_cs);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getBasinAreaHa", "getBasinAreaHa0", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setBasinAreaHa", "setBasinAreaHa1", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRatioPaddy", "getRatioPaddy2", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setRatioPaddy", "setRatioPaddy3", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRatioUplnd", "getRatioUplnd4", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setRatioUplnd", "setRatioUplnd5", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRatioForest", "getRatioForest6", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setRatioForest", "setRatioForest7", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorBasinInfowInput_cs0", "__ctorBasinInfowInput_cs0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static double getBasinAreaHa0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getBasinAreaHa()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setBasinAreaHa1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double basinAreaHa) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__real.setBasinAreaHa(basinAreaHa);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getRatioPaddy2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getRatioPaddy()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setRatioPaddy3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double ratioPaddy) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__real.setRatioPaddy(ratioPaddy);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getRatioUplnd4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getRatioUplnd()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setRatioUplnd5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double ratioUplnd) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__real.setRatioUplnd(ratioUplnd);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getRatioForest6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getRatioForest()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setRatioForest7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double ratioForest) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, @__obj);
            @__real.setRatioForest(ratioForest);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorBasinInfowInput_cs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.BasinInfowInput_cs @__real = new global::CshapJni.BasinInfowInput_cs();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__BasinInfowInput_cs(@__env);
            }
        }
    }
    #endregion
}
