//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class Cshap_Jni_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__Cshap_Jni.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.Cshap_Jni), typeof(global::CshapJni.Cshap_Jni_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.Cshap_Jni), typeof(global::CshapJni.Cshap_Jni_))]
    internal sealed partial class @__Cshap_Jni : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Cshap_Jni(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__Cshap_Jni.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Cshap_Jni);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetFloodDatas_jni", "GetFloodDatas_jni0", "(Lcshapjni/FloodReservoir_cs;Lcshapjni/FloodBasin_cs;[DDI)[Lcshapjni/FloodResult_" +
                        "cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CalReservoirWaterRateForecast_jni", "CalReservoirWaterRateForecast_jni1", "([Lcshapjni/ReservoirWaterRateForecastInput_cs;)[Lcshapjni/ReservoirWaterRateFore" +
                        "castOutput_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CalDailyPaddy_jni", "CalDailyPaddy_jni2", "([Lcshapjni/MeteoDailyData_cs;Lcshapjni/WreqPaddyInput_cs;Lcshapjni/StationInput_" +
                        "cs;)[Lcshapjni/WreqPaddyOutput_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RunByDIROM_jni", "RunByDIROM_jni3", "([Lcshapjni/MeteoDailyData_cs;Lcshapjni/BasinInfowInput_cs;)[Lcshapjni/BasinInfow" +
                        "Output_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "jni_Test", "jni_Test4", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "jni_Test_2", "jni_Test_25", "(Ljava/lang/String;)[Lcshapjni/BasinInfowOutput_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "jni_BasinInfowOutput", "jni_BasinInfowOutput6", "(Ljava/lang/String;)[Lcshapjni/BasinInfowOutput_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorCshap_Jni0", "__ctorCshap_Jni0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetFloodDatas_jni0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle FloodReservoir_jni, global::net.sf.jni4net.utils.JniLocalHandle FloodBasin_jni, global::net.sf.jni4net.utils.JniLocalHandle rains, double dt, int utype) {
            // (Lcshapjni/FloodReservoir_cs;Lcshapjni/FloodBasin_cs;[DDI)[Lcshapjni/FloodResult_cs;
            // (LCshapJni/FloodReservoir_cs;LCshapJni/FloodBasin_cs;[DDI)[LCshapJni/FloodResult_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.Cshap_Jni @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.Cshap_Jni>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.FloodResult_cs[], global::CshapJni.FloodResult_cs>(@__env, @__real.GetFloodDatas_jni(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, FloodReservoir_jni), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodBasin_cs>(@__env, FloodBasin_jni), global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, rains), dt, utype));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CalReservoirWaterRateForecast_jni1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle ReservoirWaterRateForecastInput_jni) {
            // ([Lcshapjni/ReservoirWaterRateForecastInput_cs;)[Lcshapjni/ReservoirWaterRateForecastOutput_cs;
            // ([LCshapJni/ReservoirWaterRateForecastInput_cs;)[LCshapJni/ReservoirWaterRateForecastOutput_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.Cshap_Jni @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.Cshap_Jni>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.ReservoirWaterRateForecastOutput_cs[], global::CshapJni.ReservoirWaterRateForecastOutput_cs>(@__env, @__real.CalReservoirWaterRateForecast_jni(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs[], global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, ReservoirWaterRateForecastInput_jni)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CalDailyPaddy_jni2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle MeteoDailyData_jni, global::net.sf.jni4net.utils.JniLocalHandle WreqPaddyInput_jni, global::net.sf.jni4net.utils.JniLocalHandle StationInput_jni) {
            // ([Lcshapjni/MeteoDailyData_cs;Lcshapjni/WreqPaddyInput_cs;Lcshapjni/StationInput_cs;)[Lcshapjni/WreqPaddyOutput_cs;
            // ([LCshapJni/MeteoDailyData_cs;LCshapJni/WreqPaddyInput_cs;LCshapJni/StationInput_cs;)[LCshapJni/WreqPaddyOutput_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.Cshap_Jni @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.Cshap_Jni>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.WreqPaddyOutput_cs[], global::CshapJni.WreqPaddyOutput_cs>(@__env, @__real.CalDailyPaddy_jni(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::CshapJni.MeteoDailyData_cs[], global::CshapJni.MeteoDailyData_cs>(@__env, MeteoDailyData_jni), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, WreqPaddyInput_jni), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.StationInput_cs>(@__env, StationInput_jni)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RunByDIROM_jni3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle MeteoDailyData_jni, global::net.sf.jni4net.utils.JniLocalHandle BasinInfowInput_jni) {
            // ([Lcshapjni/MeteoDailyData_cs;Lcshapjni/BasinInfowInput_cs;)[Lcshapjni/BasinInfowOutput_cs;
            // ([LCshapJni/MeteoDailyData_cs;LCshapJni/BasinInfowInput_cs;)[LCshapJni/BasinInfowOutput_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.BasinInfowOutput_cs[], global::CshapJni.BasinInfowOutput_cs>(@__env, global::CshapJni.Cshap_Jni.RunByDIROM_jni(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::CshapJni.MeteoDailyData_cs[], global::CshapJni.MeteoDailyData_cs>(@__env, MeteoDailyData_jni), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.BasinInfowInput_cs>(@__env, BasinInfowInput_jni)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle jni_Test4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle str) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.Cshap_Jni @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.Cshap_Jni>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.jni_Test(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, str)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle jni_Test_25(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle str) {
            // (Ljava/lang/String;)[Lcshapjni/BasinInfowOutput_cs;
            // (LSystem/String;)[LCshapJni/BasinInfowOutput_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.Cshap_Jni @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.Cshap_Jni>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.BasinInfowOutput_cs[], global::CshapJni.BasinInfowOutput_cs>(@__env, @__real.jni_Test_2(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, str)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle jni_BasinInfowOutput6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle str) {
            // (Ljava/lang/String;)[Lcshapjni/BasinInfowOutput_cs;
            // (LSystem/String;)[LCshapJni/BasinInfowOutput_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.Cshap_Jni @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.Cshap_Jni>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.BasinInfowOutput_cs[], global::CshapJni.BasinInfowOutput_cs>(@__env, @__real.jni_BasinInfowOutput(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, str)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorCshap_Jni0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.Cshap_Jni @__real = new global::CshapJni.Cshap_Jni();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__Cshap_Jni(@__env);
            }
        }
    }
    #endregion
}
