//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class FloodReservoirWeir_cs_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__FloodReservoirWeir_cs.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.FloodReservoirWeir_cs), typeof(global::CshapJni.FloodReservoirWeir_cs_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.FloodReservoirWeir_cs), typeof(global::CshapJni.FloodReservoirWeir_cs_))]
    internal sealed partial class @__FloodReservoirWeir_cs : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__FloodReservoirWeir_cs(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__FloodReservoirWeir_cs.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__FloodReservoirWeir_cs);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_coef_c", "get_coef_c0", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_coef_c", "set_coef_c1", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_length", "get_length2", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_length", "set_length3", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_sill_level", "get_sill_level4", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_sill_level", "set_sill_level5", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorFloodReservoirWeir_cs0", "__ctorFloodReservoirWeir_cs0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static double get_coef_c0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirWeir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirWeir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_coef_c()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_coef_c1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double coef_c) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirWeir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirWeir_cs>(@__env, @__obj);
            @__real.set_coef_c(coef_c);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_length2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirWeir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirWeir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_length()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_length3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double length) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirWeir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirWeir_cs>(@__env, @__obj);
            @__real.set_length(length);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_sill_level4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirWeir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirWeir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_sill_level()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_sill_level5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double sill_level) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirWeir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirWeir_cs>(@__env, @__obj);
            @__real.set_sill_level(sill_level);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorFloodReservoirWeir_cs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirWeir_cs @__real = new global::CshapJni.FloodReservoirWeir_cs();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__FloodReservoirWeir_cs(@__env);
            }
        }
    }
    #endregion
}
