//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class FloodReservoir_cs_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__FloodReservoir_cs.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.FloodReservoir_cs), typeof(global::CshapJni.FloodReservoir_cs_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.FloodReservoir_cs), typeof(global::CshapJni.FloodReservoir_cs_))]
    internal sealed partial class @__FloodReservoir_cs : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__FloodReservoir_cs(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__FloodReservoir_cs.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__FloodReservoir_cs);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_elevation", "get_elevation0", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_elevation", "set_elevation1", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_level_dead", "get_level_dead2", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_level_dead", "set_level_dead3", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_level_flood", "get_level_flood4", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_level_flood", "set_level_flood5", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_level_full", "get_level_full6", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_level_full", "set_level_full7", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_level_now", "get_level_now8", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_level_now", "set_level_now9", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_linears", "get_linears10", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_linears", "set_linears11", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_spillGates", "get_spillGates12", "()[Lcshapjni/FloodReservoirSpillGate_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_spillGates", "set_spillGates13", "([Lcshapjni/FloodReservoirSpillGate_cs;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_spillWeirs", "get_spillWeirs14", "()[Lcshapjni/FloodReservoirSpillWeir_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_spillWeirs", "set_spillWeirs15", "([Lcshapjni/FloodReservoirSpillWeir_cs;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_weirs", "get_weirs16", "()[Lcshapjni/FloodReservoirWeir_cs;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_weirs", "set_weirs17", "([Lcshapjni/FloodReservoirWeir_cs;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorFloodReservoir_cs0", "__ctorFloodReservoir_cs0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static double get_elevation0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_elevation()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_elevation1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double elevation) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_elevation(elevation);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_level_dead2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_level_dead()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_level_dead3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double level_dead) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_level_dead(level_dead);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_level_flood4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_level_flood()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_level_flood5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double level_flood) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_level_flood(level_flood);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_level_full6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_level_full()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_level_full7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double level_full) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_level_full(level_full);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_level_now8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_level_now()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_level_now9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double level_now) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_level_now(level_now);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle get_linears10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.get_linears());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_linears11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle linears) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_linears(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, linears));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle get_spillGates12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lcshapjni/FloodReservoirSpillGate_cs;
            // ()[LCshapJni/FloodReservoirSpillGate_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.FloodReservoirSpillGate_cs[], global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__real.get_spillGates());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_spillGates13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle spillGates) {
            // ([Lcshapjni/FloodReservoirSpillGate_cs;)V
            // ([LCshapJni/FloodReservoirSpillGate_cs;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_spillGates(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs[], global::CshapJni.FloodReservoirSpillGate_cs>(@__env, spillGates));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle get_spillWeirs14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lcshapjni/FloodReservoirSpillWeir_cs;
            // ()[LCshapJni/FloodReservoirSpillWeir_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.FloodReservoirSpillWeir_cs[], global::CshapJni.FloodReservoirSpillWeir_cs>(@__env, @__real.get_spillWeirs());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_spillWeirs15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle spillWeirs) {
            // ([Lcshapjni/FloodReservoirSpillWeir_cs;)V
            // ([LCshapJni/FloodReservoirSpillWeir_cs;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_spillWeirs(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::CshapJni.FloodReservoirSpillWeir_cs[], global::CshapJni.FloodReservoirSpillWeir_cs>(@__env, spillWeirs));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle get_weirs16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lcshapjni/FloodReservoirWeir_cs;
            // ()[LCshapJni/FloodReservoirWeir_cs;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2Jp<global::CshapJni.FloodReservoirWeir_cs[], global::CshapJni.FloodReservoirWeir_cs>(@__env, @__real.get_weirs());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_weirs17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle weirs) {
            // ([Lcshapjni/FloodReservoirWeir_cs;)V
            // ([LCshapJni/FloodReservoirWeir_cs;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoir_cs>(@__env, @__obj);
            @__real.set_weirs(global::net.sf.jni4net.utils.Convertor.ArrayStrongJp2C<global::CshapJni.FloodReservoirWeir_cs[], global::CshapJni.FloodReservoirWeir_cs>(@__env, weirs));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorFloodReservoir_cs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoir_cs @__real = new global::CshapJni.FloodReservoir_cs();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__FloodReservoir_cs(@__env);
            }
        }
    }
    #endregion
}
