//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class FloodReservoirSpillGate_cs_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__FloodReservoirSpillGate_cs.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.FloodReservoirSpillGate_cs), typeof(global::CshapJni.FloodReservoirSpillGate_cs_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.FloodReservoirSpillGate_cs), typeof(global::CshapJni.FloodReservoirSpillGate_cs_))]
    internal sealed partial class @__FloodReservoirSpillGate_cs : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__FloodReservoirSpillGate_cs(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__FloodReservoirSpillGate_cs.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__FloodReservoirSpillGate_cs);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_ap_height", "get_ap_height0", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_ap_height", "set_ap_height1", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_hd", "get_hd2", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_hd", "set_hd3", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_height", "get_height4", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_height", "set_height5", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_length", "get_length6", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_length", "set_length7", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_max_open", "get_max_open8", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_max_open", "set_max_open9", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_now_open", "get_now_open10", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_now_open", "set_now_open11", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_sill_level", "get_sill_level12", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_sill_level", "set_sill_level13", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get_slope", "get_slope14", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "set_slope", "set_slope15", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorFloodReservoirSpillGate_cs0", "__ctorFloodReservoirSpillGate_cs0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static double get_ap_height0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_ap_height()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_ap_height1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double ap_height) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_ap_height(ap_height);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_hd2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_hd()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_hd3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double hd) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_hd(hd);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_height4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_height()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_height5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double height) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_height(height);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_length6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_length()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_length7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double length) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_length(length);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_max_open8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_max_open()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_max_open9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double max_open) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_max_open(max_open);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_now_open10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_now_open()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_now_open11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double now_open) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_now_open(now_open);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_sill_level12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_sill_level()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_sill_level13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double sill_level) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_sill_level(sill_level);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double get_slope14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__return = ((double)(@__real.get_slope()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void set_slope15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double slope) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.FloodReservoirSpillGate_cs>(@__env, @__obj);
            @__real.set_slope(slope);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorFloodReservoirSpillGate_cs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.FloodReservoirSpillGate_cs @__real = new global::CshapJni.FloodReservoirSpillGate_cs();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__FloodReservoirSpillGate_cs(@__env);
            }
        }
    }
    #endregion
}
