//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class ReservoirWaterRateForecastInput_cs_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__ReservoirWaterRateForecastInput_cs.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.ReservoirWaterRateForecastInput_cs), typeof(global::CshapJni.ReservoirWaterRateForecastInput_cs_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.ReservoirWaterRateForecastInput_cs), typeof(global::CshapJni.ReservoirWaterRateForecastInput_cs_))]
    internal sealed partial class @__ReservoirWaterRateForecastInput_cs : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ReservoirWaterRateForecastInput_cs(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__ReservoirWaterRateForecastInput_cs.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ReservoirWaterRateForecastInput_cs);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFacCode", "getFacCode0", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setFacCode", "setFacCode1", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFacCat", "getFacCat2", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setFacCat", "setFacCat3", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFacName", "getFacName4", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setFacName", "setFacName5", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getBasinArea", "getBasinArea6", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setBasinArea", "setBasinArea7", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAgrArea", "getAgrArea8", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAgrArea", "setAgrArea9", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getYooHyoy", "getYooHyoy10", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setYooHyoy", "setYooHyoy11", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSigunCd", "getSigunCd12", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setSigunCd", "setSigunCd13", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getVow", "getVow14", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setVow", "setVow15", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAvgRain1", "getAvgRain116", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAvgRain1", "setAvgRain117", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAvgRain2", "getAvgRain218", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAvgRain2", "setAvgRain219", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAvgRain3", "getAvgRain320", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAvgRain3", "setAvgRain321", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getForeAvgRain1", "getForeAvgRain122", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setForeAvgRain1", "setForeAvgRain123", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getForeAvgRain2", "getForeAvgRain224", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setForeAvgRain2", "setForeAvgRain225", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getForeAvgRain3", "getForeAvgRain326", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setForeAvgRain3", "setForeAvgRain327", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFacAvg", "getFacAvg28", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setFacAvg", "setFacAvg29", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFacAvg1", "getFacAvg130", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setFacAvg1", "setFacAvg131", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFacAvg2", "getFacAvg232", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setFacAvg2", "setFacAvg233", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getFacAvg3", "getFacAvg334", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setFacAvg3", "setFacAvg335", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorReservoirWaterRateForecastInput_cs0", "__ctorReservoirWaterRateForecastInput_cs0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getFacCode0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.getFacCode());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setFacCode1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle facCode) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setFacCode(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, facCode));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getFacCat2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.getFacCat());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setFacCat3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle facCat) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setFacCat(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, facCat));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getFacName4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.getFacName());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setFacName5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle facName) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setFacName(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, facName));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getBasinArea6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getBasinArea()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setBasinArea7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double basinArea) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setBasinArea(basinArea);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getAgrArea8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getAgrArea()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setAgrArea9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double agrArea) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setAgrArea(agrArea);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getYooHyoy10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getYooHyoy()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setYooHyoy11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double yooHyoy) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setYooHyoy(yooHyoy);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getSigunCd12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.getSigunCd());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setSigunCd13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle sigunCd) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setSigunCd(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, sigunCd));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getVow14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getVow()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setVow15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double vow) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setVow(vow);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getAvgRain116(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getAvgRain1()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setAvgRain117(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double avgRain1) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setAvgRain1(avgRain1);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getAvgRain218(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getAvgRain2()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setAvgRain219(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double avgRain2) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setAvgRain2(avgRain2);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getAvgRain320(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getAvgRain3()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setAvgRain321(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double avgRain3) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setAvgRain3(avgRain3);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getForeAvgRain122(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getForeAvgRain1()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setForeAvgRain123(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double foreAvgRain1) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setForeAvgRain1(foreAvgRain1);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getForeAvgRain224(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getForeAvgRain2()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setForeAvgRain225(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double foreAvgRain2) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setForeAvgRain2(foreAvgRain2);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getForeAvgRain326(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getForeAvgRain3()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setForeAvgRain327(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double foreAvgRain3) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setForeAvgRain3(foreAvgRain3);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getFacAvg28(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getFacAvg()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setFacAvg29(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double facAvg) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setFacAvg(facAvg);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getFacAvg130(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getFacAvg1()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setFacAvg131(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double facAvg1) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setFacAvg1(facAvg1);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getFacAvg232(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getFacAvg2()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setFacAvg233(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double facAvg2) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setFacAvg2(facAvg2);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getFacAvg334(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getFacAvg3()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setFacAvg335(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double facAvg3) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.ReservoirWaterRateForecastInput_cs>(@__env, @__obj);
            @__real.setFacAvg3(facAvg3);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorReservoirWaterRateForecastInput_cs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.ReservoirWaterRateForecastInput_cs @__real = new global::CshapJni.ReservoirWaterRateForecastInput_cs();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__ReservoirWaterRateForecastInput_cs(@__env);
            }
        }
    }
    #endregion
}
