//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class WreqPaddyOutput_cs_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__WreqPaddyOutput_cs.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.WreqPaddyOutput_cs), typeof(global::CshapJni.WreqPaddyOutput_cs_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.WreqPaddyOutput_cs), typeof(global::CshapJni.WreqPaddyOutput_cs_))]
    internal sealed partial class @__WreqPaddyOutput_cs : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__WreqPaddyOutput_cs(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__WreqPaddyOutput_cs.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__WreqPaddyOutput_cs);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getYear", "getYear0", "()S"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setYear", "setYear1", "(S)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getMonth", "getMonth2", "()B"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setMonth", "setMonth3", "(B)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDay", "getDay4", "()B"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDay", "setDay5", "(B)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRainfall", "getRainfall6", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setRainfall", "setRainfall7", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getETActualMm", "getETActualMm8", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setETActualMm", "setETActualMm9", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getEffRainMm", "getEffRainMm10", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setEffRainMm", "setEffRainMm11", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDepthMm", "getDepthMm12", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDepthMm", "setDepthMm13", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getUseReqMm", "getUseReqMm14", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setUseReqMm", "setUseReqMm15", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getNetReqMm", "getNetReqMm16", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setNetReqMm", "setNetReqMm17", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getGrsReqMm", "getGrsReqMm18", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setGrsReqMm", "setGrsReqMm19", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getWreqCms", "getWreqCms20", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setWreqCms", "setWreqCms21", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDate", "getDate22", "()Lsystem/DateTime;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDate", "setDate23", "(Lsystem/DateTime;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorWreqPaddyOutput_cs0", "__ctorWreqPaddyOutput_cs0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static short getYear0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()S
            // ()S
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            short @__return = default(short);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = ((short)(@__real.getYear()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setYear1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, short year) {
            // (S)V
            // (S)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setYear(year);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static byte getMonth2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()B
            // ()B
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            byte @__return = default(byte);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = ((byte)(@__real.getMonth()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setMonth3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, byte month) {
            // (B)V
            // (B)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setMonth(month);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static byte getDay4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()B
            // ()B
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            byte @__return = default(byte);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = ((byte)(@__real.getDay()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setDay5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, byte day) {
            // (B)V
            // (B)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setDay(day);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getRainfall6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getRainfall()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setRainfall7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double rainfall) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setRainfall(rainfall);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getETActualMm8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getETActualMm());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setETActualMm9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle eTActualMm) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setETActualMm(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, eTActualMm));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getEffRainMm10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getEffRainMm());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setEffRainMm11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle effRainMm) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setEffRainMm(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, effRainMm));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getDepthMm12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getDepthMm());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setDepthMm13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle depthMm) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setDepthMm(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, depthMm));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getUseReqMm14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getUseReqMm());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setUseReqMm15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle useReqMm) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setUseReqMm(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, useReqMm));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getNetReqMm16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getNetReqMm());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setNetReqMm17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle netReqMm) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setNetReqMm(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, netReqMm));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getGrsReqMm18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getGrsReqMm());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setGrsReqMm19(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle grsReqMm) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setGrsReqMm(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, grsReqMm));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getWreqCms20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getWreqCms());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setWreqCms21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle wreqCms) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setWreqCms(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, wreqCms));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getDate22(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/DateTime;
            // ()LSystem/DateTime;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.DateTime>(@__env, @__real.getDate());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setDate23(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle date) {
            // (Lsystem/DateTime;)V
            // (LSystem/DateTime;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyOutput_cs>(@__env, @__obj);
            @__real.setDate(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.DateTime>(@__env, date));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorWreqPaddyOutput_cs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyOutput_cs @__real = new global::CshapJni.WreqPaddyOutput_cs();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__WreqPaddyOutput_cs(@__env);
            }
        }
    }
    #endregion
}
