//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapJni {
    
    
    #region Component Designer generated code 
    public partial class WreqPaddyInput_cs_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::CshapJni.@__WreqPaddyInput_cs.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::CshapJni.WreqPaddyInput_cs), typeof(global::CshapJni.WreqPaddyInput_cs_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::CshapJni.WreqPaddyInput_cs), typeof(global::CshapJni.WreqPaddyInput_cs_))]
    internal sealed partial class @__WreqPaddyInput_cs : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__WreqPaddyInput_cs(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::CshapJni.@__WreqPaddyInput_cs.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__WreqPaddyInput_cs);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getIrrAreaHa", "getIrrAreaHa0", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setIrrAreaHa", "setIrrAreaHa1", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getNonAreaHa", "getNonAreaHa2", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setNonAreaHa", "setNonAreaHa3", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getInfiltMm", "getInfiltMm4", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setInfiltMm", "setInfiltMm5", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getChLossPct", "getChLossPct6", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setChLossPct", "setChLossPct7", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDepthMaxMm", "getDepthMaxMm8", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDepthMaxMm", "setDepthMaxMm9", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDepthMinMm", "getDepthMinMm10", "()D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDepthMinMm", "setDepthMinMm11", "(D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getCropCoef", "getCropCoef12", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setCropCoef", "setCropCoef13", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getPlanDate", "getPlanDate14", "()[S"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setPlanDate", "setPlanDate15", "([S)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getUnitWReqMm", "getUnitWReqMm16", "()[D"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setUnitWReqMm", "setUnitWReqMm17", "([D)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorWreqPaddyInput_cs0", "__ctorWreqPaddyInput_cs0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getIrrAreaHa0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getIrrAreaHa());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setIrrAreaHa1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle irrAreaHa) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setIrrAreaHa(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, irrAreaHa));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getNonAreaHa2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getNonAreaHa()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setNonAreaHa3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double nonAreaHa) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setNonAreaHa(nonAreaHa);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getInfiltMm4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getInfiltMm()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setInfiltMm5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double infiltMm) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setInfiltMm(infiltMm);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getChLossPct6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getChLossPct()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setChLossPct7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double chLossPct) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setChLossPct(chLossPct);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getDepthMaxMm8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getDepthMaxMm()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setDepthMaxMm9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double depthMaxMm) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setDepthMaxMm(depthMaxMm);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static double getDepthMinMm10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()D
            // ()D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            double @__return = default(double);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = ((double)(@__real.getDepthMinMm()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setDepthMinMm11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, double depthMinMm) {
            // (D)V
            // (D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setDepthMinMm(depthMinMm);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getCropCoef12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getCropCoef());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setCropCoef13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle cropCoef) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setCropCoef(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, cropCoef));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getPlanDate14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[S
            // ()[S
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getPlanDate());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setPlanDate15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle planDate) {
            // ([S)V
            // ([S)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setPlanDate(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cshort(@__env, planDate));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getUnitWReqMm16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[D
            // ()[D
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getUnitWReqMm());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setUnitWReqMm17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle unitWReqMm) {
            // ([D)V
            // ([D)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::CshapJni.WreqPaddyInput_cs>(@__env, @__obj);
            @__real.setUnitWReqMm(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cdouble(@__env, unitWReqMm));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorWreqPaddyInput_cs0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::CshapJni.WreqPaddyInput_cs @__real = new global::CshapJni.WreqPaddyInput_cs();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::CshapJni.@__WreqPaddyInput_cs(@__env);
            }
        }
    }
    #endregion
}
